### ISSUE TITLE
Question - multiple IPs

### ISSUE THREAD

**Issue by flantel** [mr-karan/nomad-external-dns#1]
Hi,

I want to be able to add and remove IPs form a DNS A record for each traefik proxy, so if a proxy goes down the IP is removed. Is this possible? Obviously the traefik will be on different hosts. 

Thanks

**Comment by mr-karan** [comment]
Yeah, it's possible. This program would add multiple IPs to the A record in AWS R53. It's upto the client how it load balances across these IPs.
