### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by svenstaro** [mr-karan/nomad-external-dns#10]
Hey, we're unsure whether we can use this as the maintenance status seems dubious. If we created a PR, would you review and release it?

**Comment by mr-karan** [comment]
Hi. At my current org, we are using this in prod without any issues :) 

> as the maintenance status seems dubious

What do you mean by it? It's feature complete (well, atleast for the AWS R53 provider), and it just works.

> If we created a PR, would you review and release it

Sure, go ahead but file an issue beforehand please.

**Comment by svenstaro** [comment]
Ok. By dubious maintenance I meant that no dependencies have been bumped in some time, there are no tests and there wasn't any activity here for months until recently. I didn't mean offense :)
