### ISSUE TITLE
No IP address for job running in host network_mode

### ISSUE THREAD

**Issue by flantel** [mr-karan/nomad-external-dns#2]
Hi,

I am trying to use this with Traefik to update the DNS for the load balancers. Traefik is running in host mode as a system service.

It looks like if a job is using network mode = "host" or system service that the output of "nomad service list" shows "<none>" in the Address, so unable to update R53. 

Any idea of a fix?
Thanks

**Comment by flantel** [comment]
It might be nice to be able to use $NOMAD_IP_https env variable as the IP to insert into DNS.

**Comment by mr-karan** [comment]
Currently this tool only supports discovery of services if a `service` block is mentioned in the job. https://developer.hashicorp.com/nomad/docs/job-specification/service 

You could use a `service` even with host network mode.

No plans to support non-service modes as of now, since the core of the program listens to Service events which are available only via API.

**Comment by flantel** [comment]
Yes, I have a service stanza:

```
      service {
        name = "traefik"
        provider     = "nomad"
        tags = [
            "external-dns/hostname=traefik.flantel.com",
            "external-dns/ttl=30s",
      ]

```

I switched to running traefik as a service rather than system job, same result.

_nomad service info traefik_ shows: 

```
Job ID   Address  Tags                                                              Node ID   Alloc ID
traefik  <none>   [external-dns/hostname=traefik.flantel.com,external-dns/ttl=30s]  2dcb309b  0dcd60a7
traefik  <none>   [external-dns/hostname=traefik.flantel.com,external-dns/ttl=30s]  c26a9f2c  1853217b
traefik  <none>   [external-dns/hostname=traefik.flantel.com,external-dns/ttl=30s]  b5b4b352  f8834af0

```

**Comment by flantel** [comment]
I got it working by adding address = "${attr.unique.network.ip-address}" 

```
      service {
        name = "traefik"
        provider     = "nomad"
        address = "${attr.unique.network.ip-address}"
        tags = [
            "external-dns/hostname=traefik.domain.com",
            "external-dns/ttl=30s",
      ]

```

**Comment by mr-karan** [comment]
Nice. I believe just specifying `service.port` is also enough for the address to be automatically propagated.
