### ISSUE TITLE
IP not re-inserted after purge when service becomes available again

### ISSUE THREAD

**Issue by flantel** [mr-karan/nomad-external-dns#3]
I am testing with 3 traefik instances. nomad-external-dns correctly adds all three IPs to the DNS A record on startup. If I take a server offline (pausing the VM node) the downed IP is correctly purged from R53. However, when the node comes back up again the DNS records do not update to add back in the missing IP.

**Comment by mr-karan** [comment]
Can you check if the service is listed correctly after the node comes up again?

By default, it takes 10s before the program re-fetches the list of services: https://github.com/mr-karan/nomad-external-dns/blob/main/config.sample.toml#L5. You can configure this interval to be lower, based on your requirements as well.

**Comment by flantel** [comment]
Hi,

Yes, "nomad service info traefik" shows all three once the node comes back.  Perhaps it is just the way I am pausing the nomad node. I'll try shutting down the node then bringing it back up.

I'll also test manually scaling up and down the traffic service.

Thanks for your help!

-Barry Flanagan

6 Apr 2023 17:34:40 Karan Sharma ***@***.***>:

**Comment by mr-karan** [comment]
This should ideally be fixed with https://github.com/mr-karan/nomad-external-dns/pull/6
